version: "3.8"

services:
  rtpengine:
    image: readytalk/rtpengine-docker:mr6.2.1.1-39f2f23
    container_name: rtpengine
    network_mode: host
    privileged: true
    restart: unless-stopped

    volumes:
      - /dev/log:/dev/log

    command: >
      /usr/sbin/rtpengine
      --interface=172.26.26.224
      --listen-ng=22222
      --port-min=10000
      --port-max=20000
      --log-stderr
      --foreground

